# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cede6d0934f771ccfb90174fb0fb0f1"
name = "Beauty&Hair Tools"
handle = "beauty-and-hair-remix-app"
application_url = "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts,write_files,read_files,write_app_proxy,unauthenticated_read_product_listings,read_customers"

[auth]
redirect_urls = [
  "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/auth/callback",
  "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/auth/shopify/callback",
  "https://beauty-and-hair-remix-app-103600f41d3c.herokuapp.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
