# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cede6d0934f771ccfb90174fb0fb0f1"
application_url = "https://macedonia-trunk-toolbox-blend.trycloudflare.com"
embedded = true
name = "beauty-and-hair-remix-app"
handle = "beauty-and-hair-remix-app-1"

[build]
include_config_on_deploy = true
dev_store_url = "kats-dev-store.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts"

[auth]
redirect_urls = [
  "https://macedonia-trunk-toolbox-blend.trycloudflare.com/auth/callback",
  "https://macedonia-trunk-toolbox-blend.trycloudflare.com/auth/shopify/callback",
  "https://macedonia-trunk-toolbox-blend.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
