api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "discount-exclude"
type = "function"
uid = "727f6f3e-5df3-84cb-727c-12235f3763670d256070"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

[extensions.ui]
handle = "discount-exclude-block"

[extensions.input.variables]
namespace = "$app:discount-exclude"
key = "function-configuration"
