api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "discount-exclude"
uid = "727f6f3e-5df3-84cb-727c-12235f3763670d256070"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

[extensions.ui]
handle = "discount-exclude-block"

[extensions.input.variables]
namespace = "$app:discount-exclude"
key = "function-configuration"
